-- Esquema inicial para Supabase PostgreSQL.
-- Ejecutar en el SQL Editor del proyecto Supabase. No crea otra base de datos.
-- Las tablas quedan protegidas por RLS y no se agregan políticas para clientes
-- anon/authenticated. El acceso de la aplicación debe hacerse solo desde backend.

CREATE TABLE IF NOT EXISTS public.config (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  razon_social varchar(150),
  cuit char(11),
  condicion varchar(4) DEFAULT 'RI' CHECK (condicion IN ('RI','MONO')),
  punto_venta integer DEFAULT 1,
  pago_cvu char(22)
);

CREATE TABLE IF NOT EXISTS public.usuarios (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario varchar(100) UNIQUE NOT NULL,
  nombre varchar(100),
  clave varchar(255),
  rol varchar(20) CHECK (rol IN ('jefe','supervisor','encargado','repositor','cajero')),
  activo smallint NOT NULL DEFAULT 1 CHECK (activo IN (0,1)),
  fecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  otp_secret varchar(64),
  otp_enabled smallint NOT NULL DEFAULT 0 CHECK (otp_enabled IN (0,1)),
  otp_last_counter bigint NOT NULL DEFAULT -1,
  otp_recovery_codes text,
  ultimo_acceso timestamp,
  ultima_actividad timestamp
);

CREATE TABLE IF NOT EXISTS public.permisos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rol varchar(20),
  modulo varchar(50),
  accion varchar(50),
  permitido smallint NOT NULL DEFAULT 0 CHECK (permitido IN (0,1)),
  CONSTRAINT permisos_rol_modulo_accion UNIQUE (rol, modulo, accion)
);

CREATE TABLE IF NOT EXISTS public.intentos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario varchar(100),
  ip varchar(45),
  fecha timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS intentos_fecha ON public.intentos(fecha);
CREATE INDEX IF NOT EXISTS intentos_usuario_fecha ON public.intentos(usuario, fecha);
CREATE INDEX IF NOT EXISTS intentos_ip_fecha ON public.intentos(ip, fecha);

CREATE TABLE IF NOT EXISTS public.fichajes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id integer REFERENCES public.usuarios(id),
  entrada timestamp,
  salida timestamp
);
CREATE INDEX IF NOT EXISTS fichajes_usuario_entrada ON public.fichajes(usuario_id, entrada);

CREATE TABLE IF NOT EXISTS public.categorias (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(80),
  icono varchar(30) DEFAULT 'tag'
);

CREATE TABLE IF NOT EXISTS public.productos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo varchar(20) UNIQUE,
  nombre varchar(150),
  categoria_id integer REFERENCES public.categorias(id) ON DELETE SET NULL,
  precio numeric(12,2),
  iva numeric(4,2) DEFAULT 21,
  stock integer NOT NULL DEFAULT 0,
  entrante integer NOT NULL DEFAULT 0,
  minimo integer NOT NULL DEFAULT 0,
  comision_pct numeric(5,2) NOT NULL DEFAULT 0,
  costo_referencia numeric(12,2) NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS productos_nombre ON public.productos(nombre);

CREATE TABLE IF NOT EXISTS public.socios (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dni char(8) NOT NULL UNIQUE,
  nombre varchar(120) NOT NULL,
  telefono varchar(30),
  activo smallint NOT NULL DEFAULT 1 CHECK (activo IN (0,1)),
  fecha_alta timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.ventas (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cajero_id integer REFERENCES public.usuarios(id),
  socio_id integer REFERENCES public.socios(id) ON DELETE SET NULL,
  cliente varchar(150),
  doc varchar(13),
  neto numeric(12,2),
  iva numeric(12,2),
  total numeric(12,2),
  pago varchar(20),
  descuento_pct numeric(5,2) NOT NULL DEFAULT 0,
  descuento_monto numeric(12,2) NOT NULL DEFAULT 0,
  tipo char(1),
  numero integer,
  estado varchar(12) DEFAULT 'pagada',
  fecha timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ventas_fecha ON public.ventas(fecha);
CREATE INDEX IF NOT EXISTS ventas_cajero_fecha ON public.ventas(cajero_id, fecha);

CREATE TABLE IF NOT EXISTS public.pedidos_compra (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  encargado_id integer REFERENCES public.usuarios(id),
  proveedor varchar(150),
  estado varchar(20) NOT NULL DEFAULT 'pendiente'
    CHECK (estado IN ('pendiente','recibido','cancelado')),
  fecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_recibido timestamp
);
CREATE INDEX IF NOT EXISTS pedidos_compra_estado_fecha
  ON public.pedidos_compra(estado, fecha_creacion);

CREATE TABLE IF NOT EXISTS public.pedido_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id integer REFERENCES public.pedidos_compra(id),
  producto_id integer REFERENCES public.productos(id),
  cantidad integer,
  precio numeric(12,2)
);
CREATE INDEX IF NOT EXISTS pedido_items_pedido ON public.pedido_items(pedido_id);

CREATE TABLE IF NOT EXISTS public.asignaciones_caja (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id integer REFERENCES public.usuarios(id),
  caja_numero integer,
  fecha_inicio timestamp,
  fecha_fin timestamp
);
CREATE INDEX IF NOT EXISTS asignaciones_caja_usuario_activa
  ON public.asignaciones_caja(usuario_id, fecha_fin);

CREATE TABLE IF NOT EXISTS public.auditoria (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id integer REFERENCES public.usuarios(id),
  accion varchar(100),
  tabla varchar(50),
  registro_id integer,
  cambios jsonb,
  fecha timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS auditoria_fecha ON public.auditoria(fecha);

CREATE TABLE IF NOT EXISTS public.lotes_stock (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_id integer NOT NULL REFERENCES public.productos(id),
  cantidad_inicial integer NOT NULL,
  cantidad_restante integer NOT NULL,
  costo_unitario numeric(12,2) NOT NULL,
  comision_pct numeric(5,2) NOT NULL DEFAULT 0,
  precio_venta numeric(12,2) NOT NULL,
  usuario_id integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  producto_legacy_id integer UNIQUE,
  fecha timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS lotes_fifo
  ON public.lotes_stock(producto_id, cantidad_restante, fecha, id);

CREATE TABLE IF NOT EXISTS public.promociones (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(100) NOT NULL,
  tipo varchar(20) NOT NULL CHECK (tipo IN ('producto','combo')),
  precio numeric(12,2) NOT NULL,
  activa smallint NOT NULL DEFAULT 1 CHECK (activa IN (0,1)),
  fecha_inicio timestamp,
  fecha_fin timestamp,
  usuario_id integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  fecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS promociones_vigencia
  ON public.promociones(activa, fecha_inicio, fecha_fin);

CREATE TABLE IF NOT EXISTS public.promocion_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  promocion_id bigint NOT NULL REFERENCES public.promociones(id) ON DELETE CASCADE,
  producto_id integer NOT NULL REFERENCES public.productos(id),
  cantidad integer NOT NULL,
  CONSTRAINT promo_producto UNIQUE (promocion_id, producto_id)
);
CREATE INDEX IF NOT EXISTS promo_items_producto ON public.promocion_items(producto_id);

CREATE TABLE IF NOT EXISTS public.pedidos_tablet (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo char(16) NOT NULL UNIQUE,
  cliente varchar(100),
  estado varchar(20) NOT NULL DEFAULT 'pendiente'
    CHECK (estado IN ('pendiente','en_proceso','completado','cancelado')),
  cajero_id integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  venta_id integer REFERENCES public.ventas(id) ON DELETE SET NULL,
  fecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_actualizacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expira_en timestamp
);
CREATE INDEX IF NOT EXISTS cola_tablet ON public.pedidos_tablet(estado, fecha_creacion);

CREATE TABLE IF NOT EXISTS public.pedido_tablet_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id bigint NOT NULL REFERENCES public.pedidos_tablet(id) ON DELETE CASCADE,
  producto_id integer NOT NULL REFERENCES public.productos(id),
  nombre varchar(150) NOT NULL,
  cantidad integer NOT NULL,
  precio_estimado numeric(12,2) NOT NULL,
  iva numeric(4,2) NOT NULL,
  promocion_id bigint,
  promocion_nombre varchar(100),
  FOREIGN KEY (promocion_id) REFERENCES public.promociones(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS pedido_tablet ON public.pedido_tablet_items(pedido_id);

CREATE TABLE IF NOT EXISTS public.reservas_tablet (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_key char(64) NOT NULL,
  cart_key char(32) NOT NULL,
  producto_id integer NOT NULL REFERENCES public.productos(id),
  cantidad integer NOT NULL,
  promocion_id bigint REFERENCES public.promociones(id) ON DELETE SET NULL,
  precio_unitario numeric(12,2),
  pedido_id bigint REFERENCES public.pedidos_tablet(id) ON DELETE CASCADE,
  vence_en timestamp NOT NULL,
  fecha timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT reserva_linea UNIQUE (session_key, cart_key, producto_id)
);
CREATE INDEX IF NOT EXISTS reservas_producto ON public.reservas_tablet(producto_id, vence_en);
CREATE INDEX IF NOT EXISTS reservas_pedido ON public.reservas_tablet(pedido_id, vence_en);

CREATE TABLE IF NOT EXISTS public.venta_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venta_id integer REFERENCES public.ventas(id),
  producto_id integer REFERENCES public.productos(id),
  nombre varchar(150),
  cantidad integer,
  precio numeric(12,2),
  iva numeric(4,2),
  lote_id bigint REFERENCES public.lotes_stock(id) ON DELETE SET NULL,
  costo_unitario numeric(12,2),
  promocion_id bigint REFERENCES public.promociones(id) ON DELETE SET NULL,
  promocion_nombre varchar(100)
);
CREATE INDEX IF NOT EXISTS venta_items_venta ON public.venta_items(venta_id);

CREATE TABLE IF NOT EXISTS public.registro_accesos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  usuario varchar(100) NOT NULL,
  evento varchar(20) NOT NULL
    CHECK (evento IN ('login_ok','login_fallido','mfa_ok','mfa_fallido','logout')),
  ip varchar(45),
  agente varchar(255),
  fecha timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS acceso_fecha ON public.registro_accesos(fecha);
CREATE INDEX IF NOT EXISTS acceso_usuario ON public.registro_accesos(usuario_id, fecha);

INSERT INTO public.categorias(nombre, icono)
SELECT seed.nombre, seed.icono
FROM (VALUES
  ('Alimentos','basket'),
  ('Bebidas','cup-straw'),
  ('Lácteos','droplet'),
  ('Carnes y fiambres','egg-fried'),
  ('Bazar','house'),
  ('Limpieza','stars'),
  ('Perfumería','heart'),
  ('Otros','tag')
) AS seed(nombre, icono)
WHERE NOT EXISTS (SELECT 1 FROM public.categorias);

INSERT INTO public.permisos(rol, modulo, accion, permitido) VALUES
('jefe','personal','ver',1),('jefe','personal','crear',1),('jefe','personal','editar',1),('jefe','personal','eliminar',1),('jefe','personal','cambiar_permisos',1),('jefe','personal','expulsar',1),
('jefe','productos','ver',1),('jefe','productos','crear',1),('jefe','productos','editar',1),('jefe','productos','eliminar',1),
('jefe','categorias','ver',1),('jefe','categorias','crear',1),('jefe','categorias','editar',1),('jefe','categorias','eliminar',1),
('jefe','ventas','ver',1),('jefe','ventas','registrar',1),
('jefe','socios','ver',1),('jefe','socios','crear',1),('jefe','socios','editar',1),
('jefe','pedidos','ver',1),('jefe','pedidos','crear',1),('jefe','pedidos','editar',1),('jefe','pedidos','eliminar',1),
('jefe','cajas','asignar',1),('jefe','reportes','ver',1),('jefe','configuracion','ver',1),('jefe','configuracion','editar',1),
('supervisor','personal','ver',1),('supervisor','personal','crear',1),('supervisor','personal','editar',0),('supervisor','personal','eliminar',0),('supervisor','personal','cambiar_permisos',0),('supervisor','personal','expulsar',0),
('supervisor','productos','ver',1),('supervisor','productos','crear',0),('supervisor','productos','editar',1),('supervisor','productos','eliminar',0),
('supervisor','categorias','ver',1),('supervisor','categorias','crear',0),('supervisor','categorias','editar',0),('supervisor','categorias','eliminar',0),
('supervisor','ventas','ver',1),('supervisor','ventas','registrar',0),
('supervisor','socios','ver',1),('supervisor','socios','crear',1),('supervisor','socios','editar',1),
('supervisor','pedidos','ver',1),('supervisor','pedidos','crear',0),('supervisor','pedidos','editar',0),('supervisor','pedidos','eliminar',0),
('supervisor','cajas','asignar',1),('supervisor','reportes','ver',1),('supervisor','configuracion','ver',0),('supervisor','configuracion','editar',0),
('supervisor','promociones','ver',1),('supervisor','promociones','crear',1),('supervisor','promociones','editar',1),('supervisor','reponer','ver',1),
('encargado','personal','ver',1),('encargado','personal','crear',0),('encargado','personal','editar',0),('encargado','personal','eliminar',0),('encargado','personal','cambiar_permisos',0),('encargado','personal','expulsar',0),
('encargado','productos','ver',1),('encargado','productos','crear',0),('encargado','productos','editar',0),('encargado','productos','eliminar',0),
('encargado','categorias','ver',1),('encargado','categorias','crear',0),('encargado','categorias','editar',0),('encargado','categorias','eliminar',0),
('encargado','ventas','ver',1),('encargado','ventas','registrar',0),
('encargado','pedidos','ver',1),('encargado','pedidos','crear',1),('encargado','pedidos','editar',1),('encargado','pedidos','eliminar',0),
('encargado','cajas','asignar',1),('encargado','reportes','ver',1),('encargado','configuracion','ver',0),('encargado','configuracion','editar',0),('encargado','reponer','ver',1),
('repositor','personal','ver',0),('repositor','personal','crear',0),('repositor','personal','editar',0),('repositor','personal','eliminar',0),('repositor','personal','cambiar_permisos',0),('repositor','personal','expulsar',0),
('repositor','productos','ver',0),('repositor','productos','crear',0),('repositor','productos','editar',0),('repositor','productos','eliminar',0),
('repositor','categorias','ver',0),('repositor','categorias','crear',0),('repositor','categorias','editar',0),('repositor','categorias','eliminar',0),
('repositor','ventas','ver',0),('repositor','ventas','registrar',0),
('repositor','pedidos','ver',0),('repositor','pedidos','crear',0),('repositor','pedidos','editar',0),('repositor','pedidos','eliminar',0),
('repositor','cajas','asignar',0),('repositor','reportes','ver',0),('repositor','configuracion','ver',0),('repositor','configuracion','editar',0),('repositor','reponer','ver',1),
('cajero','personal','ver',0),('cajero','personal','crear',0),('cajero','personal','editar',0),('cajero','personal','eliminar',0),('cajero','personal','cambiar_permisos',0),('cajero','personal','expulsar',0),
('cajero','productos','ver',1),('cajero','productos','crear',0),('cajero','productos','editar',0),('cajero','productos','eliminar',0),
('cajero','categorias','ver',1),('cajero','categorias','crear',0),('cajero','categorias','editar',0),('cajero','categorias','eliminar',0),
('cajero','ventas','ver',1),('cajero','ventas','registrar',1),
('cajero','pedidos','ver',0),('cajero','pedidos','crear',0),('cajero','pedidos','editar',0),('cajero','pedidos','eliminar',0),
('cajero','cajas','asignar',0),('cajero','reportes','ver',0),('cajero','configuracion','ver',0),('cajero','configuracion','editar',0)
ON CONFLICT (rol, modulo, accion) DO NOTHING;

ALTER TABLE public.config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.permisos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.intentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fichajes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ventas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.socios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pedido_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pedidos_compra ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.asignaciones_caja ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.auditoria ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lotes_stock ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promociones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promocion_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pedidos_tablet ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pedido_tablet_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reservas_tablet ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.venta_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.registro_accesos ENABLE ROW LEVEL SECURITY;
